-- ============================================
-- RESET DATABASE TO VIRGIN STATE
-- ============================================
-- Tujuan: Menghapus SEMUA DATA tanpa merusak schema
-- AMAN: Schema, migration, constraints tetap utuh
-- ============================================

BEGIN;

-- Disable foreign key checks temporarily (PostgreSQL doesn't need this, but for safety)
SET session_replication_role = 'replica';

-- ============================================
-- TRUNCATE ALL TABLES (in dependency order)
-- ============================================

-- Core Content Tables
TRUNCATE TABLE "BlogProduct" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BlogTag" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Blog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BlogPost" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BlogCategory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BlogKeyword" RESTART IDENTITY CASCADE;

-- Product Tables
TRUNCATE TABLE "ProductImage" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductWholesalePrice" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Product" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductCategory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProductStats" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CatalogProduct" RESTART IDENTITY CASCADE;

-- AI & Content Generation
TRUNCATE TABLE "AIContentQueue" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AIContentSettings" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AIContentGenerationLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentVersion" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentJob" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentResult" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentSchedule" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentCategory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentExpansion" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentDistribution" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentRefresh" RESTART IDENTITY CASCADE;

-- SEO Tables
TRUNCATE TABLE "SeoMetadata" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoEntity" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoKeyword" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoKeywordMapping" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoInternalLink" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoOnPageOptimization" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoOptimizationLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoBlogQueue" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoSitemapEntry" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoIndexingSubmission" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoCrawlIssue" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoBrokenLink" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoWebVitals" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoPageAuthority" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoContentCluster" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoImageIntelligence" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoEngineLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoEngineStatus" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoScheduledTask" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoEngineFailure" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "LocalSeoPage" RESTART IDENTITY CASCADE;

-- Scheduler & Automation
TRUNCATE TABLE "SchedulerConfig" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SchedulerRun" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SchedulerExecutionLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SchedulerTask" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SchedulerTaskRun" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SchedulerStatsDaily" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ScheduleKeyword" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AutomationJob" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AutomationLog" RESTART IDENTITY CASCADE;

-- Engine & System
TRUNCATE TABLE "EngineLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineHealth" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineAlert" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineHeartbeat" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineControl" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineBusLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineBusMetrics" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DataHandoff" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EngineFeedbackLoop" RESTART IDENTITY CASCADE;

-- Analytics & Tracking
TRUNCATE TABLE "AnalyticsVisit" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AnalyticsSession" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AnalyticsCTAClick" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AnalyticsDailySummary" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AnalyticsLocationStats" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AnalyticsDeviceStats" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "analytics_snapshot" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "TrackingEvent" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "VisitorCache" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "UserBehavior" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Session" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SessionPage" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "RepeatVisitor" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Subscriber" RESTART IDENTITY CASCADE;

-- Marketing & Ads
TRUNCATE TABLE "AdCampaign" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdCreative" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdPerformance" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdPerformanceAggregate" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdStrategyReport" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "WinningAdSet" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdSetLearning" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdSetCluster" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdSetPerformanceLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AutoGeneratedAdSet" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdSetRecommendation" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SmartAdInsight" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SmartAdAudience" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SmartAdRecommendation" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "MarketingCampaign" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CampaignPerformance" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CampaignAttribution" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "MarketingIntegration" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "MarketingEventMap" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "MarketingEventLog" RESTART IDENTITY CASCADE;

-- Intelligence & Learning
TRUNCATE TABLE "KeywordIntelligence" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "KeywordInterestMapping" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdsInterestMapping" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "LearningSnapshot" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AiLearningMemory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "WinningContentPattern" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ContentTemplate" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BehavioralDecisionLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ErrorPatternDB" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PriorityMatrix" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "MasterDecision" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "MasterDecisionLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SmartFeedbackLoop" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DeviceBehaviorInsight" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AudienceCluster" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdsLocationRecommendation" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DevicePricing" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "UserMarketProfile" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProfitSignalScore" RESTART IDENTITY CASCADE;

-- Entity & Schema
TRUNCATE TABLE "BrandEntity" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AuthorEntity" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AuthorProfile" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EntityMention" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EntitySchema" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "TopicalAuthorityCluster" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EntityLink" RESTART IDENTITY CASCADE;

-- Links & Redirects
TRUNCATE TABLE "InternalLink" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "InternalLinkRule" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "UrlRedirect" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ProgrammaticPage" RESTART IDENTITY CASCADE;

-- System & Admin
TRUNCATE TABLE "AuditLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ActivityLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "EventLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ActionApproval" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ActionTrace" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SystemAlert" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SystemIntegrationConfig" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "IntegrationAuditLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdminPasswordResetToken" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "AdminPasswordResetAttempt" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "WhatsAppAdmin" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SalesAdmin" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PublicInquiry" RESTART IDENTITY CASCADE;

-- Partners
TRUNCATE TABLE "Partner" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PartnerScope" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PartnerSession" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PartnerAuditLog" RESTART IDENTITY CASCADE;

-- Other
TRUNCATE TABLE "ImageServiceAPIKey" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SocialProofLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Location" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "IndexPingLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CrawlPriority" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SeoHealthIssue" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "FailureMemory" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "FailureMemoryBlockLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BounceIntervention" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "BounceInterventionInteraction" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "LayoutAdaptation" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CtaConfig" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CtaClick" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Post" RESTART IDENTITY CASCADE;

-- ============================================
-- PRESERVE: Brand, Locale, Admin, SiteSettings
-- ============================================
-- These are configuration tables, NOT test data
-- If you want to reset these too, uncomment:
-- TRUNCATE TABLE "Brand" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "Locale" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "Admin" RESTART IDENTITY CASCADE;
-- TRUNCATE TABLE "SiteSettings" RESTART IDENTITY CASCADE;

-- Re-enable foreign key checks
SET session_replication_role = 'origin';

COMMIT;

-- ============================================
-- VERIFICATION QUERIES
-- ============================================
-- Run these after reset to verify:

-- SELECT COUNT(*) FROM "Blog"; -- Should be 0
-- SELECT COUNT(*) FROM "Product"; -- Should be 0
-- SELECT COUNT(*) FROM "AIContentGenerationLog"; -- Should be 0
-- SELECT COUNT(*) FROM "SchedulerExecutionLog"; -- Should be 0
