-- ============================================
-- RESET DATABASE KE KONDISI VIRGIN (AGGRESSIVE)
-- ============================================
-- Versi lebih agresif yang menggunakan DELETE sebagai fallback
-- Tujuan: Memastikan SEMUA data benar-benar terhapus
-- ============================================

BEGIN;

-- Disable triggers sementara untuk menghindari constraint issues
SET session_replication_role = 'replica';

-- ============================================
-- STEP 1: DELETE semua data (lebih agresif dari TRUNCATE)
-- ============================================

-- Core Content
DELETE FROM "BlogProduct";
DELETE FROM "BlogTag";
DELETE FROM "Blog";
DELETE FROM "BlogPost";
DELETE FROM "BlogCategory";
DELETE FROM "BlogKeyword";

-- Products (harus sebelum ProductCategory karena ada foreign key)
DELETE FROM "ProductImage";
DELETE FROM "ProductWholesalePrice";
DELETE FROM "Product";
DELETE FROM "ProductCategory";

-- Content Management
DELETE FROM "ContentVersion";
DELETE FROM "ContentCategory";
DELETE FROM "ContentJob";
DELETE FROM "ContentResult";
DELETE FROM "ContentSchedule";
DELETE FROM "ContentTemplate";
DELETE FROM "ContentExpansion";
DELETE FROM "ContentRefresh";
DELETE FROM "ContentDistribution";

-- AI & Generation
DELETE FROM "AIContentGenerationLog";
DELETE FROM "AIContentQueue";
DELETE FROM "AIContentSettings";
DELETE FROM "AiLearningMemory";

-- SEO & Keywords
DELETE FROM "SeoImageIntelligence";
DELETE FROM "SeoContentCluster";
DELETE FROM "SeoPageAuthority";
DELETE FROM "SeoWebVitals";
DELETE FROM "SeoBrokenLink";
DELETE FROM "SeoCrawlIssue";
DELETE FROM "SeoIndexingSubmission";
DELETE FROM "SeoSitemapEntry";
DELETE FROM "SeoBlogQueue";
DELETE FROM "SeoOptimizationLog";
DELETE FROM "SeoOnPageOptimization";
DELETE FROM "SeoInternalLink";
DELETE FROM "SeoKeywordMapping";
DELETE FROM "SeoKeyword";
DELETE FROM "SeoEntity";
DELETE FROM "SeoMetadata";
DELETE FROM "SeoEngineFailure";
DELETE FROM "SeoScheduledTask";
DELETE FROM "SeoEngineStatus";
DELETE FROM "SeoEngineLog";

-- Scheduler
DELETE FROM "SchedulerTaskRun";
DELETE FROM "SchedulerTask";
DELETE FROM "SchedulerStatsDaily";
DELETE FROM "SchedulerExecutionLog";
DELETE FROM "SchedulerRun";
DELETE FROM "SchedulerConfig";
DELETE FROM "ScheduleKeyword";

-- Engine & Automation
DELETE FROM "AutomationLog";
DELETE FROM "AutomationJob";
DELETE FROM "EngineBusMetrics";
DELETE FROM "EngineBusLog";
DELETE FROM "EngineControl";
DELETE FROM "EngineHeartbeat";
DELETE FROM "EngineAlert";
DELETE FROM "EngineHealth";
DELETE FROM "EngineLog";

-- Internal Linking
DELETE FROM "EntityLink";
DELETE FROM "EntityMention";
DELETE FROM "EntitySchema";
DELETE FROM "TopicalAuthorityCluster";
DELETE FROM "InternalLinkRule";
DELETE FROM "InternalLink";

-- Analytics & Tracking
DELETE FROM "AnalyticsSnapshot";
DELETE FROM "AnalyticsDeviceStats";
DELETE FROM "AnalyticsLocationStats";
DELETE FROM "AnalyticsDailySummary";
DELETE FROM "AnalyticsCTAClick";
DELETE FROM "AnalyticsSession";
DELETE FROM "AnalyticsVisit";
DELETE FROM "TrackingEvent";
DELETE FROM "ProductStats";
DELETE FROM "VisitorCache";
DELETE FROM "SessionPage";
DELETE FROM "Session";
DELETE FROM "RepeatVisitor";
DELETE FROM "Subscriber";
DELETE FROM "UserBehavior";

-- Marketing & Ads
DELETE FROM "CampaignAttribution";
DELETE FROM "CampaignPerformance";
DELETE FROM "MarketingEventLog";
DELETE FROM "MarketingEventMap";
DELETE FROM "MarketingIntegration";
DELETE FROM "AdStrategyReport";
DELETE FROM "AdPerformanceAggregate";
DELETE FROM "AdPerformance";
DELETE FROM "AdCreative";
DELETE FROM "AdCampaign";

-- Intelligence & Learning
DELETE FROM "SmartAdRecommendation";
DELETE FROM "SmartAdAudience";
DELETE FROM "SmartAdInsight";
DELETE FROM "AdsLocationRecommendation";
DELETE FROM "AudienceCluster";
DELETE FROM "DeviceBehaviorInsight";
DELETE FROM "AdSetRecommendation";
DELETE FROM "AutoGeneratedAdSet";
DELETE FROM "SmartFeedbackLoop";
DELETE FROM "AdSetPerformanceLog";
DELETE FROM "AdSetCluster";
DELETE FROM "AdSetLearning";
DELETE FROM "WinningAdSet";
DELETE FROM "AdsInterestMapping";
DELETE FROM "KeywordInterestMapping";
DELETE FROM "ProfitSignalScore";
DELETE FROM "UserMarketProfile";
DELETE FROM "DevicePricing";
DELETE FROM "KeywordIntelligence";
DELETE FROM "WinningContentPattern";

-- Decision & Behavioral
DELETE FROM "LearningSnapshot";
DELETE FROM "BehavioralDecisionLog";
DELETE FROM "MasterDecisionLog";
DELETE FROM "MasterDecision";

-- Failure & Error Tracking
DELETE FROM "PriorityMatrix";
DELETE FROM "ErrorPatternDB";
DELETE FROM "FailureMemoryBlockLog";
DELETE FROM "FailureMemory";

-- System & Audit
DELETE FROM "IntegrationAuditLog";
DELETE FROM "SystemIntegrationConfig";
DELETE FROM "ActionTrace";
DELETE FROM "ActionApproval";
DELETE FROM "ActivityLog";
DELETE FROM "EventLog";
DELETE FROM "SystemAlert";
DELETE FROM "AuditLog";

-- Programmatic Pages
DELETE FROM "UrlRedirect";
DELETE FROM "LocalSeoPage";
DELETE FROM "ProgrammaticPage";

-- Other Content
DELETE FROM "CatalogProduct";
DELETE FROM "Post";

-- Media & Assets
DELETE FROM "ImageServiceAPIKey";
DELETE FROM "SocialProofLog";

-- Location & Indexing
DELETE FROM "SeoHealthIssue";
DELETE FROM "CrawlPriority";
DELETE FROM "IndexPingLog";
DELETE FROM "Location";

-- Author & Entity
DELETE FROM "AuthorProfile";
DELETE FROM "AuthorEntity";
DELETE FROM "BrandEntity";

-- Bounce & Layout
DELETE FROM "EngineFeedbackLoop";
DELETE FROM "LayoutAdaptation";
DELETE FROM "BounceInterventionInteraction";
DELETE FROM "BounceIntervention";

-- Data Handoff
DELETE FROM "DataHandoff";

-- CTA
DELETE FROM "CtaClick";
DELETE FROM "CtaConfig";

-- Public & Sales
DELETE FROM "SalesAdmin";
DELETE FROM "PublicInquiry";

-- Partner
DELETE FROM "PartnerAuditLog";
DELETE FROM "PartnerSession";
DELETE FROM "PartnerScope";
DELETE FROM "Partner";

-- WhatsApp
DELETE FROM "WhatsAppAdmin";

-- Admin (KEEP ADMIN USERS - hanya reset password reset tokens)
DELETE FROM "AdminPasswordResetAttempt";
DELETE FROM "AdminPasswordResetToken";

-- ============================================
-- STEP 2: RESET IDENTITY (auto-increment)
-- ============================================

-- Reset semua sequence untuk auto-increment
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN 
        SELECT schemaname, sequencename 
        FROM pg_sequences 
        WHERE schemaname = 'public'
    LOOP
        EXECUTE 'ALTER SEQUENCE ' || quote_ident(r.schemaname) || '.' || quote_ident(r.sequencename) || ' RESTART WITH 1';
    END LOOP;
END $$;

-- Re-enable triggers
SET session_replication_role = 'origin';

COMMIT;

-- ============================================
-- VERIFIKASI
-- ============================================
-- Jalankan query berikut untuk memastikan semua tabel kosong:
-- 
-- SELECT 
--   schemaname,
--   tablename,
--   n_live_tup as row_count
-- FROM pg_stat_user_tables
-- WHERE schemaname = 'public'
--   AND tablename NOT IN ('Brand', 'Locale', 'Admin', 'SiteSettings', '_prisma_migrations')
-- ORDER BY row_count DESC, tablename;
-- 
-- Semua row_count harus = 0
