-- ============================================
-- RESET DATABASE KE KONDISI VIRGIN
-- ============================================
-- Tujuan: TRUNCATE semua data tanpa merusak schema
-- AMAN: Schema, migration, dan kontrak PHASE A tetap utuh
-- ============================================

BEGIN;

-- Disable foreign key checks temporarily (PostgreSQL doesn't need this, but included for clarity)
-- PostgreSQL handles CASCADE automatically

-- TRUNCATE semua tabel data dengan RESTART IDENTITY CASCADE
-- CASCADE akan menghapus data dari tabel yang memiliki foreign key ke tabel ini

TRUNCATE TABLE
  -- Core Content
  "Blog",
  "BlogPost",
  "BlogCategory",
  "BlogTag",
  "BlogProduct",
  "BlogKeyword",
  
  -- Products
  "Product",
  "ProductImage",
  "ProductCategory",
  "ProductWholesalePrice",
  
  -- Content Management
  "ContentVersion",
  "ContentCategory",
  "ContentJob",
  "ContentResult",
  "ContentSchedule",
  "ContentTemplate",
  "ContentExpansion",
  "ContentRefresh",
  "ContentDistribution",
  
  -- AI & Generation
  "AIContentQueue",
  "AIContentGenerationLog",
  "AIContentSettings",
  "AiLearningMemory",
  
  -- SEO & Keywords
  "SeoMetadata",
  "SeoEntity",
  "SeoKeyword",
  "SeoKeywordMapping",
  "SeoInternalLink",
  "SeoOnPageOptimization",
  "SeoOptimizationLog",
  "SeoBlogQueue",
  "SeoSitemapEntry",
  "SeoIndexingSubmission",
  "SeoCrawlIssue",
  "SeoBrokenLink",
  "SeoWebVitals",
  "SeoPageAuthority",
  "SeoContentCluster",
  "SeoImageIntelligence",
  "SeoEngineLog",
  "SeoEngineStatus",
  "SeoScheduledTask",
  "SeoEngineFailure",
  
  -- Scheduler
  "ScheduleKeyword",
  "SchedulerConfig",
  "SchedulerRun",
  "SchedulerExecutionLog",
  "SchedulerTask",
  "SchedulerTaskRun",
  "SchedulerStatsDaily",
  
  -- Engine & Automation
  "EngineLog",
  "EngineHealth",
  "EngineAlert",
  "EngineHeartbeat",
  "EngineControl",
  "EngineBusLog",
  "EngineBusMetrics",
  "AutomationJob",
  "AutomationLog",
  
  -- Internal Linking
  "InternalLink",
  "InternalLinkRule",
  "EntityLink",
  "EntityMention",
  "EntitySchema",
  
  -- Analytics & Tracking
  "AnalyticsVisit",
  "AnalyticsSession",
  "AnalyticsCTAClick",
  "AnalyticsDailySummary",
  "AnalyticsLocationStats",
  "AnalyticsDeviceStats",
  "AnalyticsSnapshot",
  "TrackingEvent",
  "ProductStats",
  "VisitorCache",
  "Session",
  "SessionPage",
  "RepeatVisitor",
  "Subscriber",
  "UserBehavior",
  
  -- Marketing & Ads
  "AdCampaign",
  "AdCreative",
  "AdPerformance",
  "AdPerformanceAggregate",
  "AdStrategyReport",
  "MarketingIntegration",
  "MarketingEventMap",
  "MarketingEventLog",
  "CampaignPerformance",
  "CampaignAttribution",
  
  -- Intelligence & Learning
  "KeywordIntelligence",
  "WinningContentPattern",
  "WinningAdSet",
  "AdSetLearning",
  "AdSetCluster",
  "AdSetPerformanceLog",
  "SmartFeedbackLoop",
  "AutoGeneratedAdSet",
  "AdSetRecommendation",
  "DeviceBehaviorInsight",
  "AudienceCluster",
  "AdsLocationRecommendation",
  "SmartAdInsight",
  "SmartAdAudience",
  "SmartAdRecommendation",
  "KeywordInterestMapping",
  "AdsInterestMapping",
  "UserMarketProfile",
  "ProfitSignalScore",
  "DevicePricing",
  
  -- Decision & Behavioral
  "MasterDecision",
  "MasterDecisionLog",
  "BehavioralDecisionLog",
  "TopicalAuthorityCluster",
  "LearningSnapshot",
  
  -- Failure & Error Tracking
  "FailureMemory",
  "FailureMemoryBlockLog",
  "ErrorPatternDB",
  "PriorityMatrix",
  
  -- System & Audit
  "AuditLog",
  "EventLog",
  "ActivityLog",
  "ActionApproval",
  "ActionTrace",
  "SystemAlert",
  "SystemIntegrationConfig",
  "IntegrationAuditLog",
  
  -- Programmatic Pages
  "ProgrammaticPage",
  "LocalSeoPage",
  "UrlRedirect",
  
  -- Other Content
  "Post",
  "CatalogProduct",
  
  -- Media & Assets
  "SocialProofLog",
  "ImageServiceAPIKey",
  
  -- Location & Indexing
  "Location",
  "IndexPingLog",
  "CrawlPriority",
  "SeoHealthIssue",
  
  -- Author & Entity
  "AuthorEntity",
  "AuthorProfile",
  "BrandEntity",
  
  -- Bounce & Layout
  "BounceIntervention",
  "BounceInterventionInteraction",
  "LayoutAdaptation",
  "EngineFeedbackLoop",
  
  -- Data Handoff
  "DataHandoff",
  
  -- CTA
  "CtaConfig",
  "CtaClick",
  
  -- Public & Sales
  "PublicInquiry",
  "SalesAdmin",
  
  -- Partner
  "Partner",
  "PartnerScope",
  "PartnerSession",
  "PartnerAuditLog",
  
  -- WhatsApp
  "WhatsAppAdmin",
  
  -- Admin (KEEP ADMIN USERS - hanya reset password reset tokens)
  "AdminPasswordResetToken",
  "AdminPasswordResetAttempt"

RESTART IDENTITY CASCADE;

-- Catatan: Tabel berikut TIDAK dihapus karena merupakan konfigurasi sistem:
-- - Brand (konfigurasi brand)
-- - Locale (konfigurasi bahasa)
-- - Admin (user admin - tetap ada)
-- - SiteSettings (pengaturan sistem)

COMMIT;

-- Verifikasi: Jalankan query berikut untuk memastikan semua tabel kosong
-- SELECT 
--   schemaname,
--   tablename,
--   n_tup_ins as row_count
-- FROM pg_stat_user_tables
-- WHERE schemaname = 'public'
-- ORDER BY tablename;
